### ISSUE TITLE
Ability to star a song

### ISSUE THREAD

**Issue by banjoe-zz** [Doraemoe/Spotify-Plugin-for-Quicksilver#1]
This project looks very promising. Have you received requests to add the "star" song to the action list?

**Comment by Doraemoe** [comment]
Hi, thanks for your comment. Yes, I'm preparing an update that will allows you to "star" a song as well as manipulate playlist, but I don't have much time recently, so it might take a little longer.

**Comment by Doraemoe** [comment]
Hi,
I add the ability to star a song in the advanced version. However, due to the inclusion of libspotify framework, the plugin size increased dramatically, besides, you need to login in the preference panel in order to use this function. It's still in beta, so it might be unstable. You can try it if you want, I have provided the download link in the readme file.

**Comment by Doraemoe** [comment]
Well, since Spotify dropped the support of "star" and replaced it with My Library, I've add "save" action to add a song to My Library, this issue will be closed.
