### ISSUE TITLE
how do you install this?

### ISSUE THREAD

**Issue by kidbrax** [Doraemoe/Spotify-Plugin-for-Quicksilver#13]
how do you install this?

**Comment by Doraemoe** [comment]
Please download from the [release page](https://github.com/Doraemoe/Spotify-Plugin-for-Quicksilver/releases/) Then you could double click to install.

If you cannot login, please refer to the [Wiki](https://github.com/Doraemoe/Spotify-Plugin-for-Quicksilver/wiki/Login-page-does-not-load). 

Since I have switched to Apple Music, I haven't updated this plugin for a long time. If it does not work, please let me know and I will have a look if I can fix it.

**Comment by kidbrax** [comment]
perfect, thanks
