### ISSUE TITLE
Latest Spotify release breaks the plugin

### ISSUE THREAD

**Issue by jgandt** [Doraemoe/Spotify-Plugin-for-Quicksilver#4]
A new update to spotify seems to have broken the plugin.

The version installed on my machine is: 1.0.1.1060.gc......

I have no idea how to debug this. If you can point me towards some debug resources I may be able to provide more information.

This plugin is absolutely critical to my use of quicksilver.

**Comment by Doraemoe** [comment]
Hi,
Could you please describe what problems you have met? Dose this plugin broken all together or just part of it? I might be able to look into it within this week.

**Comment by Doraemoe** [comment]
OK, It seems the problem is because the new version of Spotify completely removed Apple Script support, I'm not sure if this is intended or just a mistake. According to [this thread](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/td-p/1029434) it could just be a bug, maybe they will fix it in the next update.

**Comment by jgandt** [comment]
Thanks so much for the quick response! I figured it would be something like this. Here's to hoping that they patch this in their next build!

As an FYI:

The workaround in the spotify thread you linked above works.

To get this to work I:

1) quit spotify
2) made the specified change to the Info.plist file
3) restarted spotify
4) quit and restarted quicksilver

**Comment by jgandt** [comment]
Confirmed most recent release for Spotify fixed this.
